// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Placeholder is enough for `prisma generate` (Vercel postinstall / CI).
    // Real migrate/push/seed commands still need a live DATABASE_URL.
    url: process.env.DATABASE_URL ?? "postgresql://127.0.0.1:5432/placeholder",
  },
});
